repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        types: [python]
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: check-added-large-files
        args: ["--maxkb=1500"]
        exclude: >
          (^data/KnoxCounty_Buildings\.geojson$|
           ^data/tl_2023_47093_roads\.shp$|
           ^data/tl_2023_47093_roads\.dbf$|
           ^data/Built_Surface_1990\.tif$|
           ^data/Built_Surface_2020\.tif$|
           ^outputs/OLS_Regression_Residuals_vs_Fitted_Values\.png$|
           ^outputs/Built_Surface_Change_1990_to_2020\.png$|
           ^outputs/Built_Surface_Change_1990_to_2020_test\.png$|
           ^outputs/GWR_Local_R2_Test\.png$)

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black-jupyter

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args:
          [
            "--ignore-words-list=aci,acount,acounts,fallow,ges,hart,hist,nd,ned,ois,wqs,watermask,tre,mape",
            "--skip=*.csv,*.geojson,*.json,*.yml,*.js,*.html,*.cff,*.pdf",
          ]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
