site_name: lsttrends
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Contributing: contributing.md
  - FAQ: faq.md
  - Changelog: changelog.md
  - Report Issues: https://github.com/amccorketutoring/lsttrends/issues
  - Examples:
      - Preprocessing: examples/preprocessing.md
      - OLS Regression: examples/stats_ols.md
      - GWR Analysis: examples/stats_gwr.md
      - Moran's I: examples/spatial_analysis.md
      - Change Detection: examples/change_detection.md
      - Clustering Radar Chart: examples/clustering.md
      - UHI Vulnerability: examples/uhi_vulnerability.md
      - GEE Data Prep: examples/gee.md
      - GEE Integration: examples/gee_integration.md
  - Modules:
      - Preprocessing: modules/preprocessing.md
      - Change Detection: modules/change_detection.md
      - OLS Regression: modules/stats_ols.md
      - GWR Analysis: modules/stats_gwr.md
      - Spatial Autocorrelation: modules/spatial_analysis.md
      - Clustering & Radar Chart: modules/clustering.md
      - Vulnerability Index: modules/uhi_vulnerability.md
  - API Reference:
      - lsttrends module: lsttrends.md
      - common module: common.md
      - summer_trend module: api/summer_trend.md
